### ISSUE TITLE
dowload blocked by virusscanner, specific trojan mentioned. please review

### ISSUE THREAD

**Issue by ekkonap** [ricaun/RevitLookup.Installation#3]
download link https://github.com/ricaun/RevitLookup.Installation/releases/download/2022.0.1.0/RevitLookup.2022.0.1.0.zip
lead my virusscanner to object, reporting this link to contain
Trojan:Script/Wacatac.B!ml

please review, cant be too carefull these days.

**Comment by ricaun** [comment]
That's really strange...  My virus scanner doesn't fire anything.

I use the same `iss` script in this repo.

The link: https://github.com/ricaun/RevitLookup.Installation/releases/download/2022.0.0.14/RevitLookup.2022.0.0.14.zip triggers something in your antivirus?!

**Comment by ricaun** [comment]
This project gonna be archived, check the new MSI package on the main RevitLookup project.

* https://github.com/jeremytammik/RevitLookup

**Comment by ekkonap** [comment]
> That's really strange... My virus scanner doesn't fire anything.
> 
> I use the same `iss` script in this repo.
> 
> The link: https://github.com/ricaun/RevitLookup.Installation/releases/download/2022.0.0.14/RevitLookup.2022.0.0.14.zip triggers something in your antivirus?!

That link triggers the same response, with Microsoft Defender. Will check out the new MSI package. Thanks!
